name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  LOCAL: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    permissions: "write-all"

    runs-on: ubuntu-latest
    steps:

      # Checkouts the codez
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      # Make sure we can build/run the container, and set the commit hash as a step output
      - name: Deploy to container
        id: docker-build
        run: |
          make docker-run
          export CURR_HASH=$(git rev-parse --short HEAD)
          echo "::set-output name=CURR_HASH::${CURR_HASH}"

      # Do the version bump for the commit
      - name: Push Version Tag
        id: version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DEFAULT_BUMP: ${{ secrets.VERSION_BUMP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      # Creds for Dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag and Push image to Dockerhub
      - name: Push Release to Dockerhub
        env:
          VERSION_TAG: ${{ steps.version.outputs.tag }}
          DOCKER_REPO: "${{ secrets.DOCKER_USER }}/go-github-boiler"
          CURR_HASH: ${{ steps.docker-build.outputs.CURR_HASH }}
        run: |
          export VERSION="$(echo "${VERSION_TAG}" | sed "s|v||g")"
          docker tag ${DOCKER_REPO} ${DOCKER_REPO}:${VERSION}
          docker push -a ${DOCKER_REPO}
