name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout the latest
      - name: Checkout code
        uses: actions/checkout@v2

      # Get version
      - name: Git Version
        uses: codacy/git-version@2.2.0
        with:
          dev-branch: "develop"
          release-branch: "main"

      # Bump Version
      - name: Tag Release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "autobot@thecodenomad.com"
          git config --global user.name "Autobot"
          git tag -a "v${VERSION}" -m "Releasing version ${VERSION}"
          git push origin "v${VERSION}"
