name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    permissions: "write-all"

    runs-on: ubuntu-latest
    steps:

      # Checkouts the codez
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      # Do the version bump jig
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DEFAULT_BUMP: "patch"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
