name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    permissions: "write-all"

    runs-on: ubuntu-latest
    steps:

      # Checkouts the codez
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      # Do the version bump jig
      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DEFAULT_BUMP: ${{ secrets.VERSION_BUMP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Push tagged docker image to reference version
      - name: Tag Container with Version
        env:
          LOCAL: 0
          VERSION_TAG: ${{ steps.version.outputs.tag }}
          DOCKER_REPO: "codenomad/go-github-boiler"
        run: |
          export CURR_HASH=$(git rev-parse --short HEAD)
          export VERSION="$(echo "${VERSION_TAG}" | sed "s|v||g")"
          docker pull ${DOCKER_REPO}:${CURR_HASH}
          docker tag ${DOCKER_REPO}:${CURR_HASH} ${DOCKER_REPO}:${VERSION}
          docker push ${DOCKER_REPO}:${VERSION}